name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  run-check:
    uses: ./.github/workflows/check.yml
    secrets:
      API_TOKEN: ${{ secrets.API_TOKEN }}

  docker-build:
    uses: ./.github/workflows/docker-build.yml
    needs: run-check

  run-test:
    uses: ./.github/workflows/test.yml
    needs: docker-build
    secrets:
      API_TOKEN: ${{ secrets.API_TOKEN }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    with:
      APPS: ${{ vars.APPS }}
      API_URL: ${{ vars.API_URL }}
      DB_NAME: ${{ vars.DB_NAME }}
      DB_HOST: ${{ vars.DB_HOST }}  
      DB_PORT: ${{ vars.DB_PORT }}
      API_USER: ${{ vars.API_USER }}