name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  run-check:
    uses: ./.github/workflows/check.yml
    secrets:
      API_TOKEN: ${{ secrets.API_TOKEN }}

  docker-build:
    uses: ./.github/workflows/docker-build.yml
    needs: run-check

  run-test:
    uses: ./.github/workflows/test.yml
    needs: docker-build
    secrets:
      API_TOKEN: ${{ secrets.API_TOKEN }}
